### ISSUE TITLE
🐛 [FIX] Matching @AuthMember 적용

### ISSUE THREAD

**Issue by pse10307** [jinho7/UMC_SmuPool_GroupD_BE#45]
## 🐞 버그 내용
- Matching @AuthMember 적용

## ✔️ To-Do
- [ ]Matching @AuthMember 적용

## 👀 ETC
- 참고자료 등 기타 내용 작성

## ⏰ 예상 소요 시간
- ~ 까지 완료 예정

**Comment by jinho7** [comment]
수고하셨습니다!
